from pathlib import Path
import sys

ROOT = Path(sys.argv[1])
MAP = ROOT / "StikDebug" / "Views" / "MapSelectionView.swift"
if not MAP.exists():
    raise SystemExit(f"Missing source file: {MAP}")

text = MAP.read_text(encoding="utf-8")

# Persistent A -> B route bookmarks. Stored in UserDefaults so they survive
# app restarts and do not depend on the current map selection.
model_marker = "private struct RouteSearchSelection {\n    let title: String\n    let coordinate: CLLocationCoordinate2D\n}\n"
model_insert = model_marker + '''\nprivate struct SavedRouteBookmark: Codable, Identifiable, Equatable {\n    let id: UUID\n    var name: String\n    var startTitle: String\n    var startLatitude: Double\n    var startLongitude: Double\n    var endTitle: String\n    var endLatitude: Double\n    var endLongitude: Double\n\n    var startSelection: RouteSearchSelection {\n        RouteSearchSelection(\n            title: startTitle,\n            coordinate: CLLocationCoordinate2D(latitude: startLatitude, longitude: startLongitude)\n        )\n    }\n\n    var endSelection: RouteSearchSelection {\n        RouteSearchSelection(\n            title: endTitle,\n            coordinate: CLLocationCoordinate2D(latitude: endLatitude, longitude: endLongitude)\n        )\n    }\n}\n\nprivate enum SavedRouteBookmarkStore {\n    private static let key = "savedRouteBookmarks"\n\n    static func load() -> [SavedRouteBookmark] {\n        guard let data = UserDefaults.standard.data(forKey: key),\n              let routes = try? JSONDecoder().decode([SavedRouteBookmark].self, from: data) else {\n            return []\n        }\n        return routes\n    }\n\n    static func save(_ routes: [SavedRouteBookmark]) {\n        guard let data = try? JSONEncoder().encode(routes) else { return }\n        UserDefaults.standard.set(data, forKey: key)\n    }\n}\n'''
if model_marker not in text:
    raise SystemExit("RouteSearchSelection marker not found")
text = text.replace(model_marker, model_insert, 1)

state_marker = '''    @State private var isResolvingSelection = false\n    @State private var errorMessage: String?\n    @FocusState private var focusedField: RouteSearchField?\n'''
state_insert = '''    @State private var isResolvingSelection = false\n    @State private var errorMessage: String?\n    @State private var savedRouteBookmarks: [SavedRouteBookmark] = []\n    @State private var showSavedRoutes = false\n    @State private var showSaveRoute = false\n    @State private var newRouteName = ""\n    @FocusState private var focusedField: RouteSearchField?\n'''
if state_marker not in text:
    raise SystemExit("RouteSearchSheet state marker not found")
text = text.replace(state_marker, state_insert, 1)

body_toolbar_marker = '''            .toolbar {\n                ToolbarItem(placement: .cancellationAction) {\n                    Button("Cancel") {\n                        dismiss()\n                    }\n                }\n\n                ToolbarItem(placement: .confirmationAction) {\n                    Button("Use Route") {\n                        guard let startSelection, let endSelection else { return }\n                        onApply(startSelection, endSelection)\n                        dismiss()\n                    }\n                    .disabled(!canApply)\n                }\n            }\n        }\n        .presentationDetents([.medium, .large])\n        .onAppear {\n'''
body_toolbar_new = '''            .toolbar {\n                ToolbarItem(placement: .cancellationAction) {\n                    HStack(spacing: 14) {\n                        Button {\n                            showSavedRoutes = true\n                        } label: {\n                            Image(systemName: "bookmark.fill")\n                        }\n                        .accessibilityLabel("已收藏路線")\n\n                        Button("Cancel") {\n                            dismiss()\n                        }\n                    }\n                }\n\n                ToolbarItem(placement: .confirmationAction) {\n                    HStack(spacing: 10) {\n                        Button {\n                            showSaveRoute = true\n                        } label: {\n                            Image(systemName: "bookmark")\n                        }\n                        .disabled(!canApply)\n                        .accessibilityLabel("收藏目前路線")\n\n                        Button("Use Route") {\n                            guard let startSelection, let endSelection else { return }\n                            onApply(startSelection, endSelection)\n                            dismiss()\n                        }\n                        .disabled(!canApply)\n                    }\n                }\n            }\n        }\n        .sheet(isPresented: $showSavedRoutes) {\n            SavedRoutesView(\n                routes: savedRouteBookmarks,\n                onSelect: { route in\n                    startSelection = route.startSelection\n                    endSelection = route.endSelection\n                    startQuery = route.startTitle\n                    endQuery = route.endTitle\n                    showSavedRoutes = false\n                    onApply(route.startSelection, route.endSelection)\n                    dismiss()\n                },\n                onDelete: { offsets in\n                    savedRouteBookmarks.remove(atOffsets: offsets)\n                    SavedRouteBookmarkStore.save(savedRouteBookmarks)\n                }\n            )\n        }\n        .alert("收藏路線", isPresented: $showSaveRoute) {\n            TextField("路線名稱", text: $newRouteName)\n            Button("儲存") { saveCurrentRoute() }\n            Button("取消", role: .cancel) { newRouteName = "" }\n        } message: {\n            Text("將目前的起點與終點儲存起來，下次可直接選擇。")\n        }\n        .presentationDetents([.medium, .large])\n        .onAppear {\n            savedRouteBookmarks = SavedRouteBookmarkStore.load()\n'''
if body_toolbar_marker not in text:
    raise SystemExit("RouteSearchSheet toolbar marker not found")
text = text.replace(body_toolbar_marker, body_toolbar_new, 1)

# Add save helper immediately before routeField().
helper_marker = '''    private func routeField(\n'''
helper = '''    private func saveCurrentRoute() {\n        guard let startSelection, let endSelection else { return }\n\n        let trimmedName = newRouteName.trimmingCharacters(in: .whitespacesAndNewlines)\n        let name = trimmedName.isEmpty\n            ? "\\(startSelection.title) → \\(endSelection.title)"\n            : trimmedName\n\n        let route = SavedRouteBookmark(\n            id: UUID(),\n            name: name,\n            startTitle: startSelection.title,\n            startLatitude: startSelection.coordinate.latitude,\n            startLongitude: startSelection.coordinate.longitude,\n            endTitle: endSelection.title,\n            endLatitude: endSelection.coordinate.latitude,\n            endLongitude: endSelection.coordinate.longitude\n        )\n\n        savedRouteBookmarks.append(route)\n        SavedRouteBookmarkStore.save(savedRouteBookmarks)\n        newRouteName = ""\n    }\n\n    private func routeField(\n'''
if helper_marker not in text:
    raise SystemExit("routeField marker not found")
text = text.replace(helper_marker, helper, 1)

# Append the saved-route list before the existing location bookmark sheet.
bookmark_marker = "// MARK: - Bookmarks Sheet\n"
saved_view = '''private struct SavedRoutesView: View {\n    let routes: [SavedRouteBookmark]\n    let onSelect: (SavedRouteBookmark) -> Void\n    let onDelete: (IndexSet) -> Void\n\n    var body: some View {\n        NavigationStack {\n            Group {\n                if routes.isEmpty {\n                    ContentUnavailableView(\n                        "尚無收藏路線",\n                        systemImage: "bookmark.slash",\n                        description: Text("先設定起點與終點，再按書籤圖示收藏。")\n                    )\n                } else {\n                    List {\n                        ForEach(routes) { route in\n                            Button {\n                                onSelect(route)\n                            } label: {\n                                VStack(alignment: .leading, spacing: 5) {\n                                    Text(route.name)\n                                        .foregroundStyle(.primary)\n                                        .font(.headline)\n                                    Text("\\(route.startTitle) → \\(route.endTitle)")\n                                        .foregroundStyle(.primary)\n                                    Text(String(format: "%.6f, %.6f → %.6f, %.6f", route.startLatitude, route.startLongitude, route.endLatitude, route.endLongitude))\n                                        .font(.caption.monospaced())\n                                        .foregroundStyle(.secondary)\n                                }\n                                .padding(.vertical, 4)\n                            }\n                        }\n                        .onDelete(perform: onDelete)\n                    }\n                }\n            }\n            .navigationTitle("收藏路線")\n            .navigationBarTitleDisplayMode(.inline)\n        }\n        .presentationDetents([.medium, .large])\n    }\n}\n\n'''
if bookmark_marker not in text:
    raise SystemExit("Bookmarks Sheet marker not found")
text = text.replace(bookmark_marker, saved_view + bookmark_marker, 1)

MAP.write_text(text, encoding="utf-8")
print("A-to-B route bookmark feature applied.")
